# conda env create --file environment.yml
name: webpage_phishing_detection
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - pip
  - pyprojroot
  - python=3.4.5
  - pip:
    - pyhere
    